# Google Cloud Build CI/CD Pipeline
# This is the equivalent of .gitlab-ci.yml for Google Cloud

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west8-docker.pkg.dev/$PROJECT_ID/app-mod-workshop/app-mod-workshop:$COMMIT_SHA'
      - '-t'
      - 'europe-west8-docker.pkg.dev/$PROJECT_ID/app-mod-workshop/app-mod-workshop:latest'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west8-docker.pkg.dev/$PROJECT_ID/app-mod-workshop/app-mod-workshop:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west8-docker.pkg.dev/$PROJECT_ID/app-mod-workshop/app-mod-workshop:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'app-mod-workshop'
      - '--image'
      - 'europe-west8-docker.pkg.dev/$PROJECT_ID/app-mod-workshop/app-mod-workshop:$COMMIT_SHA'
      - '--region'
      - 'europe-west8'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_HOST=/cloudsql/$PROJECT_ID:europe-west8:appmod-phpapp'
      - '--set-env-vars'
      - 'DB_NAME=image_catalog'
      - '--set-env-vars'
      - 'DB_USER=appmod-phpapp'
      - '--set-secrets'
      - 'DB_PASSWORD=db-user-password:latest'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:europe-west8:appmod-phpapp'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'

  # Import database schema (only if tables don't exist)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Check if tables exist, if not, import schema
        if ! gcloud sql databases describe image_catalog --instance=appmod-phpapp --quiet; then
          echo "Database not found, creating..."
          gcloud sql databases create image_catalog --instance=appmod-phpapp
        fi
        
        # Import schema if tables don't exist
        TABLE_COUNT=$(gcloud sql connect appmod-phpapp --user=root --quiet --command="SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'image_catalog';" 2>/dev/null | tail -1 || echo "0")
        
        if [ "$TABLE_COUNT" = "0" ]; then
          echo "Importing database schema..."
          gcloud sql import sql appmod-phpapp gs://$PROJECT_ID-sql-imports/schema.sql --database=image_catalog
        fi

# Store build artifacts
images:
  - 'europe-west8-docker.pkg.dev/$PROJECT_ID/app-mod-workshop/app-mod-workshop:$COMMIT_SHA'
  - 'europe-west8-docker.pkg.dev/$PROJECT_ID/app-mod-workshop/app-mod-workshop:latest'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the build
timeout: '1200s' 