steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/app-mod-workshop/app-mod-workshop:$COMMIT_SHA'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/app-mod-workshop/app-mod-workshop:prod-latest'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/app-mod-workshop/app-mod-workshop:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/app-mod-workshop/app-mod-workshop:prod-latest'

  # Deploy to Cloud Run PROD
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'app-mod-workshop-prod'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/app-mod-workshop/app-mod-workshop:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_HOST=34.154.174.181'
      - '--set-env-vars'
      - 'DB_NAME=image_catalog'
      - '--set-env-vars'
      - 'DB_USER=appmod-phpapp'
      - '--set-env-vars'
      - 'DB_PASSWORD=appmod-phpapp'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '100'
      - '--min-instances'
      - '1'

# Store build artifacts
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/app-mod-workshop/app-mod-workshop:$COMMIT_SHA'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/app-mod-workshop/app-mod-workshop:prod-latest'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the build
timeout: '1200s' 