services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./uploads:/var/www/html/uploads
    environment:
      - DB_HOST=db
      - DB_NAME=image_catalog
      - DB_USER=app_user
      - DB_PASSWORD=app_password
    networks:
      - app-network

  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: image_catalog
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge 